/*
  The Swaminarayan vocabulary, and the instructions that go with it.

  Ported from the Aashirwad Captions bridge run by the American mandirs
  (`realtime-transcription`, Vijay Patel et al.), which has been captioning the
  same sampradaya's sermons for longer than this has. Their glossary and context
  block are field experience with our exact vocabulary, and re-deriving them
  from scratch would have cost a season of Sundays.

  These are the defaults. `soniox.contextTerms` and `soniox.translationTerms` in
  config.json are added on top and win on conflict, so a mandir with its own
  usage overrides without editing this file. Set `soniox.builtInGlossary` to
  false to run on local terms alone.
*/

/** A source phrase and the exact English it must become. */
export interface TranslationTerm {
  source: string;
  target: string;
}

/** Instruction pairs. Soniox caps the whole context object at 8,000 tokens. */
export interface ContextEntry {
  key: string;
  value: string;
}

/**
 * Words to expect in the audio. These bias transcription only — they say
 * nothing about what the English should be.
 */
export const BUILT_IN_CONTEXT_TERMS: readonly string[] = [
  "જય શ્રી સ્વામિનારાયણ",
  "જય સ્વામિનારાયણ",
  "જય",
  "સ્વામિનારાયણ બાપા",
  "સ્વામિનારાયણ",
  "સહજાનંદ",
  "શ્રીજી",
  "ઘનશ્યામ",
  "શ્રી ઘનશ્યામ મહારાજ રજત પ્રતિષ્ઠા મહોત્સવ",
  "રજત મહોત્સવ",
  "રજત",
  "પરમેશ્વર",
  "વચનામૃત",
  "વચનામૃત મહાગ્રંથની",
  "ગઢડા",
  "ગઢડા મધ્ય પ્રકરણ",
  "હરિજ્ઞાનામૃત કાવ્ય",
  "હરિજ્ઞાનામૃત",
  "શિખર",
  "શિક્ષાપત્રી",
  "સત્સંગી જીવન",
  "પુરુષોત્તમ",
  "અક્ષરધામ",
  "આચાર્ય",
  "સ્વામીશ્રી",
  "મહારાજ",
  "શ્રી મુક્તજીવન સ્વામીબાપા",
  "મુક્તજીવન સ્વામીબાપા",
  "જીવનપ્રાણ સ્વામીબાપા",
  "સ્વામીબાપા",
  "સ્વામી બાપા",
  "મુક્તજીવન",
  "જીવનપ્રાણ",
  "બાપાશ્રી",
  "પ્રાતઃસ્મરણીયા બાપાશ્રી",
  "પ્રાતઃસ્મરણીય",
  "પ્રાતઃસ્મરણીયા",
  "પ્રાતસ્મરણીય",
  "પ્રાતસ્મણીયા",
  "Pratah Smaraniya",
  "ગુરુદેવ",
  "પધરામણી",
  "ઠાકોરજી",
  "માણિનગર",
  "સત્સંગ",
  "સમયો",
  "સમયાના",
  "સમયાની",
  "સમયામાં",
  "Samayo",
  "રાસ",
  "જંગલી રાસ",
  "ધર્મ સમ્રાટ",
  "પરમ પૂજ્ય",
  "પુરુષોત્તમપ્રિય",
  "દ્વિભુજ",
  "ચતુર્ભુજ",
  "વૃત્તિ",
  "બ્રહ્મ યજ્ઞ",
  "દિવાળી",
  "ભરાસર",
  "યજમાન",
  "બે",
  "વીસ",
  "બસો",
  "બસ્સો",
  "નાદ વંશી",
  "નાદવંશી",
  "રાજી",
  "Nad Vanshi",
  "Nairobi",
  "Parkland",
  "Gavada",
  "Mokhasan",
  "ગવાડા",
  "મોખાસન",
  "મોકાસણ",
  "Secaucus",
  "શિકાકસ",
  "સિકૉકસ",
  "સિકોકસ",
  "Akhil Swami",
  "Akhil",
  "चतुर्भुज",
  "शिखर",
  "राजी",
];

/**
 * Exact English for a source phrase. Longest first, because Soniox matches
 * greedily and "જય" would otherwise shadow "જય શ્રી સ્વામિનારાયણ".
 *
 * Soft bias, not a rule: Soniox paraphrases these often enough that
 * `normalizeTranslation` exists to catch what slips through.
 */
export const BUILT_IN_TRANSLATION_TERMS: readonly TranslationTerm[] = [
  { source: "જય શ્રી સ્વામિનારાયણ", target: "Jay Shree Swaminarayan" },
  { source: "જય સ્વામિનારાયણ", target: "Jay Swaminarayan" },
  { source: "જય શ્રી કૃષ્ણ", target: "Jay Shree Krishna" },
  { source: "જય", target: "Jay" },
  { source: "जय श्री स्वामिनारायण", target: "Jay Shree Swaminarayan" },
  { source: "जय स्वामिनारायण", target: "Jay Swaminarayan" },
  { source: "जय", target: "Jay" },
  { source: "સ્વામિનારાયણ બાપા", target: "Swaminarayan Bapa" },
  { source: "સ્વામિનારાયણ", target: "Swaminarayan" },
  { source: "ભગવાન", target: "Bhagwan" },
  { source: "સહજાનંદ", target: "Sahjanand" },
  { source: "શ્રીજી", target: "Shreeji" },
  { source: "હરિકૃષ્ણ", target: "Harikrushna" },
  { source: "ઘનશ્યામ", target: "Ghanshyam" },
  { source: "વચનામૃત", target: "Vachanamrut" },
  { source: "વચનામૃત મહાગ્રંથની", target: "Vachanamrut Scripture" },
  { source: "ગઢડા", target: "Gadhada" },
  { source: "ગરડા", target: "Gadhada" },
  { source: "હરિજ્ઞાનામૃત કાવ્ય", target: "Harignanamrut Kavya" },
  { source: "હરિજ્ઞાનામૃત", target: "Harignanamrut" },
  { source: "કાવ્ય", target: "kavya" },
  { source: "શિખર", target: "Shikhar" },
  { source: "शिखर", target: "Shikhar" },
  { source: "શિક્ષાપત્રી", target: "Shikshapatri" },
  { source: "સત્સંગી જીવન", target: "Satsangi Jeevan" },
  { source: "ગ્રંથ", target: "granth" },
  { source: "મંત્ર", target: "mantra" },
  { source: "શ્લોક", target: "shlok" },
  { source: "પરમેશ્વર", target: "Parameshwar" },
  { source: "નારાયણ", target: "Narayan" },
  { source: "હરિ", target: "Hari" },
  { source: "અક્ષર", target: "Akshar" },
  { source: "અક્ષરધામ", target: "Akshardham" },
  { source: "પુરુષોત્તમ", target: "Purushottam" },
  { source: "પૂર્ણ પુરુષોત્તમ", target: "Purna Purushottam" },
  { source: "સર્વોપરી", target: "Sarvopari" },
  { source: "સર્વાવતારી", target: "Sarvavatari" },
  { source: "આચાર્ય", target: "Acharya" },
  { source: "પુરુષોત્તમપ્રિય", target: "Purushottampriya" },
  { source: "પરમ પૂજ્ય", target: "Param Pujya" },
  { source: "સ્વામીશ્રી", target: "Swamishree" },
  { source: "સ્વામીજી", target: "Swamiji" },
  { source: "મહારાજ", target: "Maharaj" },
  { source: "ધર્મ સમ્રાટ", target: "Dharma Samrat" },
  { source: "પરમ કલ્યાણકારી", target: "Param Kalyankari" },
  { source: "વિશ્વ વાત્સલ્ય", target: "Vishwa Vatsalya" },
  { source: "પંચમ વારસદાર", target: "Pancham Varasdar" },
  { source: "ધર્મ ધુરંધર", target: "Dharma Dhurandhar" },
  { source: "શ્રી મુક્તજીવન સ્વામીબાપા", target: "Shree Muktajeevan Swamibapa" },
  { source: "મુક્તજીવન સ્વામીબાપા", target: "Muktajeevan Swamibapa" },
  { source: "જીવનપ્રાણ સ્વામીબાપા", target: "Jeevanpran Swamibapa" },
  { source: "જીવનપ્રાણ સ્વામી બાપા", target: "Jeevanpran Swamibapa" },
  { source: "સ્વામીબાપા", target: "Swamibapa" },
  { source: "સ્વામી બાપા", target: "Swamibapa" },
  { source: "મુક્તજીવન", target: "Muktajeevan" },
  { source: "જીવનપ્રાણ", target: "Jeevanpran" },
  { source: "પ્રાતઃસ્મરણીયા બાપાશ્રી", target: "Pratah Smaraniya Bapashree" },
  { source: "પ્રાતઃસ્મરણીય બાપાશ્રી", target: "Pratah Smaraniya Bapashree" },
  { source: "પ્રાતસ્મરણીયા બાપાશ્રી", target: "Pratah Smaraniya Bapashree" },
  { source: "પ્રાતસ્મણીયા બાપાશ્રી", target: "Pratah Smaraniya Bapashree" },
  { source: "પ્રાતઃસ્મરણીયા", target: "Pratah Smaraniya" },
  { source: "પ્રાતઃસ્મરણીય", target: "Pratah Smaraniya" },
  { source: "પ્રાતસ્મરણીયા", target: "Pratah Smaraniya" },
  { source: "પ્રાતસ્મરણીય", target: "Pratah Smaraniya" },
  { source: "પ્રાતસ્મણીયા", target: "Pratah Smaraniya" },
  { source: "બાપાશ્રી", target: "Bapashree" },
  { source: "ગુરુદેવ", target: "Gurudev" },
  { source: "સદ્ગુરુ", target: "Sadguru" },
  { source: "સ્વામી", target: "Swami" },
  { source: "શ્રી", target: "Shree" },
  { source: "મુક્ત", target: "mukt" },
  { source: "મુક્ત મંડળ", target: "Mukt Mandal" },
  { source: "સંપ્રદાય", target: "sampraday" },
  { source: "ગાદી", target: "Gadi" },
  { source: "સંસ્થાન", target: "Sansthan" },
  { source: "માણિનગર", target: "Maninagar" },
  { source: "ભરાસર", target: "Bharasar" },
  { source: "નાદ વંશી", target: "Nad Vanshi" },
  { source: "નાદવંશી", target: "Nad Vanshi" },
  { source: "Nad Vanshi", target: "Nad Vanshi" },
  { source: "બસ્સો", target: "two hundred" },
  { source: "બસો", target: "two hundred" },
  { source: "વીસ", target: "twenty" },
  { source: "બે", target: "two" },
  { source: "આરતી", target: "aarti" },
  { source: "મંગળા આરતી", target: "mangla aarti" },
  { source: "કીર્તન", target: "kirtan" },
  { source: "જંગલી રાસ", target: "jungle raas" },
  { source: "રાસ", target: "raas" },
  { source: "ભક્તિ", target: "bhakti" },
  { source: "પ્રતિષ્ઠા", target: "pratishtha" },
  { source: "પ્રાણ પ્રતિષ્ઠા", target: "prana pratishtha" },
  { source: "મૂર્તિ", target: "murti" },
  { source: "સિંહાસન", target: "sinhasan" },
  { source: "ગર્ભગૃહ", target: "garbhagruh" },
  { source: "નગર યાત્રા", target: "nagar yatra" },
  { source: "આશીર્વાદ", target: "ashirwad" },
  { source: "પધરામણી", target: "Padhramni" },
  { source: "દર્શન", target: "darshan" },
  { source: "પ્રસાદ", target: "prasad" },
  { source: "થાળ", target: "thaal" },
  { source: "ઠાકોરજી", target: "Thakorji" },
  { source: "પૂજા", target: "pooja" },
  { source: "પૂજન", target: "poojan" },
  { source: "નિયમ", target: "niyam" },
  { source: "સભા", target: "sabha" },
  { source: "સત્સંગ", target: "satsang" },
  { source: "વિચરણ", target: "vicharan" },
  { source: "ધ્યાન", target: "dhyan" },
  { source: "ધૂન", target: "dhoon" },
  { source: "પારાયણ", target: "parayan" },
  { source: "પ્રાર્થના", target: "prarthna" },
  { source: "મંગળાચરણ", target: "mangalacharan" },
  { source: "અન્નકૂટ", target: "annakut" },
  { source: "ગુરુપૂર્ણિમા", target: "Gurupurnima" },
  { source: "ભજન", target: "bhajan" },
  { source: "મંદિર", target: "mandir" },
  { source: "શ્રી ઘનશ્યામ મહારાજ રજત પ્રતિષ્ઠા મહોત્સવ", target: "Shree Ghanshyam Maharaj Rajat Pratishta Mahotsav" },
  { source: "રજત પ્રતિષ્ઠા મહોત્સવ", target: "Rajat Pratishta Mahotsav" },
  { source: "રજત મહોત્સવ", target: "Rajat Mahotsav" },
  { source: "રજત", target: "Rajat" },
  { source: "મહોત્સવ", target: "Mahotsav" },
  { source: "સમયામાં", target: "Samayo" },
  { source: "સમયાના", target: "Samayo" },
  { source: "સમયાની", target: "Samayo" },
  { source: "સમયો", target: "Samayo" },
  { source: "ઉત્સવ", target: "utsav" },
  { source: "તિલક", target: "tilak" },
  { source: "પ્રણામ", target: "pranam" },
  { source: "બ્રહ્મ યજ્ઞ", target: "Brahma yagna" },
  { source: "યજ્ઞ", target: "yagna" },
  { source: "હવન", target: "havan" },
  { source: "દીક્ષા", target: "diksha" },
  { source: "શિરોમણિ", target: "Shiromani" },
  { source: "સંત", target: "sant" },
  { source: "સંતો", target: "santo" },
  { source: "હરિભક્ત", target: "haribhakta" },
  { source: "હરિભક્તો", target: "haribhakto" },
  { source: "બંધુઓ", target: "devotees" },
  { source: "બાપાની", target: "Bapa's" },
  { source: "ચરણ", target: "charan" },
  { source: "ધામ", target: "dham" },
  { source: "સેવા", target: "seva" },
  { source: "ધર્મ", target: "dharma" },
  { source: "જ્ઞાન", target: "gnan" },
  { source: "સ્વરૂપ", target: "swaroop" },
  { source: "સંકલ્પ", target: "sankalp" },
  { source: "કૃપા", target: "krupa" },
  { source: "મહિમા", target: "mahima" },
  { source: "રાજી", target: "happy" },
  { source: "राजी", target: "happy" },
  { source: "આનંદ", target: "anand" },
  { source: "અંતઃકરણ", target: "antahkaran" },
  { source: "ઇન્દ્રિયો", target: "indriyo" },
  { source: "દેહ", target: "deh" },
  { source: "ત્યાગ", target: "tyaag" },
  { source: "આસક્તિ", target: "asakti" },
  { source: "બ્રહ્મ", target: "Brahma" },
  { source: "વૃત્તિ", target: "vrutti" },
  { source: "અંશ", target: "ansh" },
  { source: "તેજ", target: "tej" },
  { source: "સમર્થ", target: "Samarth" },
  { source: "પ્રત્યક્ષ", target: "pratyaksh" },
  { source: "સનાતન", target: "sanatan" },
  { source: "અખંડ", target: "akhand" },
  { source: "દ્રષ્ટિ", target: "drashti" },
  { source: "આશરો", target: "aashro" },
  { source: "આજ્ઞા", target: "agna" },
  { source: "યજમાન પદ", target: "sponsor role" },
  { source: "યજમાન", target: "sponsor" },
  { source: "ધજા", target: "dhaja" },
  { source: "વિષય", target: "vishay" },
  { source: "તેજોમય", target: "radiant" },
  { source: "આત્મા", target: "atma" },
  { source: "આત્મનિષ્ઠા", target: "atmanishtha" },
  { source: "મુમુક્ષુ", target: "mumukshu" },
  { source: "કલ્યાણ", target: "kalyaan" },
  { source: "મુક્તિ", target: "mukti" },
  { source: "વૈરાગ્ય", target: "vairagya" },
  { source: "જીવ", target: "jeev" },
  { source: "ઈશ્વર", target: "Ishwar" },
  { source: "પ્રગટ", target: "pragat" },
  { source: "દ્વિભુજ", target: "two-armed" },
  { source: "ચતુર્ભુજ", target: "four-armed" },
  { source: "द्विभुज", target: "two-armed" },
  { source: "चतुर्भुज", target: "four-armed" },
  { source: "દિવાળી", target: "Diwali" },
  { source: "પાટોત્સવ", target: "patotsav" },
  { source: "કથા વાર્તા", target: "katha varta" },
  { source: "અખિલ સ્વામી", target: "Akhil Swami" },
  { source: "ગવાડા", target: "Gavada" },
  { source: "Gavada", target: "Gavada" },
  { source: "મોખાસન", target: "Mokhasan" },
  { source: "મોકાસણ", target: "Mokhasan" },
  { source: "Mokhasan", target: "Mokhasan" },
  { source: "નૈરોબી", target: "Nairobi" },
  { source: "પાર્કલેન્ડ", target: "Parkland" },
  { source: "શિકાકસ", target: "Secaucus" },
  { source: "સિકૉકસ", target: "Secaucus" },
  { source: "સિકોકસ", target: "Secaucus" },
  { source: "સેકૉકસ", target: "Secaucus" },
  { source: "સેકોકસ", target: "Secaucus" },
];

/**
 * What the audio is and how the English should read. This is where the register
 * is set — a sermon is not a podcast, and a literal translation of devotional
 * Gujarati can land somewhere between odd and offensive on a public broadcast.
 */
export const BUILT_IN_GENERAL_CONTEXT: readonly ContextEntry[] = [
  {
    key: "source_language",
    value:
      "Gujarati-primary sermon monologue (single speaker — a teacher delivering religious discourse for the Shree Swaminarayan Gadi) with Hindi and English code-switching in the same sentences (place names, modern terms, person names, short English phrases) — not separate speakers or caption lines. language_hints include gu, hi, en with enable_language_identification so English fragments are recognized as English within the flow.",
  },
  {
    key: "target_language",
    value:
      "English",
  },
  {
    key: "domain",
    value:
      "Swaminarayan satsang and pravachan; bhajan, kirtan, katha, and devout discourse grounded in scriptures such as the Vachanamrut, Shikshapatri, Satsangi Jeevan, and Harignanamrut Kavya — always religious, never secular entertainment or romance.",
  },
  {
    key: "audience",
    value:
      "Mass public live captions (temple hall, YouTube/OBS overlay, families and children present). Formal Swaminarayan / Hindu devotional register only — clarity and readable grammar matter more than lowest latency. Prefer grace, blessings, divine presence, mercy, and devotion over ordinary physical, romantic, or slang English; captions must never sound like secular pop lyrics or suggestive speech. Never output sexual, romantic-suggestive, vulgar, abusive, hateful, violent-threat, or otherwise malicious English — no swear words, slurs, crude slang, or internet-meme tone. If a literal wording would sound inappropriate for a public religious broadcast, choose a respectful devout paraphrase that preserves the spiritual meaning. God, Guru, or murti 'touching', 'holding', 'coming near', or 'meeting' a devotee means spiritual grace, krupa, blessings, or divine presence — never physical contact: prefer 'bestowed grace', 'touched with grace', 'blessed', 'graced the devotee'; never suggestive or awkward secular phrasing (e.g. 'he touched me'). Bhajan and kirtan lines stay devout hymn language.",
  },
  {
    key: "honorific_names",
    value:
      "Use translation_terms targets exactly — never paraphrase glossary items. Names of God, gurus, sants, and acharyas are proper names: transliterate them, never translate their literal meaning. This applies to any name carrying a title or prefix such as Maharaj, Swami, Swamibapa, Bapa, Sant, Guru, Acharya, or Shree (e.g. Ghanshyam Maharaj, Akhil Swami — never rendered as English words; never translate a given name to an English word). સ્વામીબાપા / સ્વામી બાપા is always the proper name Swamibapa (one word, never 'Swami Bapa'); જીવનપ્રાણ is the honorific Jeevanpran (never life-breath, lifeblood, or 'life-breath of our life'); મુક્તજીવન is Muktajeevan (never translate the parts); formal titles Jeevanpran Swamibapa, Muktajeevan Swamibapa, and Shree Muktajeevan Swamibapa stay intact. જય = Jay, never Jai. When the speaker uses English words or standard English place/person names inside Gujarati speech, keep correct English spelling in the translation (Nairobi, Parkland, Secaucus) — never phonetic garble (Naimobi, Patland, Shikakas). દ્વિભુજ / द्विभुज = two-armed and ચતુર્ભુજ / चतुर्भुज = four-armed divine form (Krishna, Narayan, Swaminarayan murti) — never bipedal, bi-pedal, or two-legged.",
  },
  {
    key: "translation_style",
    value:
      "Treat each translation result as part of a continuous sermon, not an isolated phrase. Preserve subjects, pronouns, conjunctions, and referents from the preceding thought. Do not turn a clause fragment into a standalone sentence or add artificial sentence boundaries. Produce natural, grammatical English without inventing missing content. Translate into well-formed complete English sentences a reader can follow on their own, reading as continuous speech: connect related ideas with normal syntax; avoid semicolon chains, em-dash phrase stacks, and one-word or orphan fragments (e.g. 'Together.' or 'And that.'); merge repeated wording into one natural phrase; keep who/what/when clear; preserve meaning and tone. For death and bereavement references, use formal compassionate religious phrasing such as 'the late ...' or '... who has passed away'; never use blunt 'dead [person]' labels or awkward possessive constructions. When a phrase appears in translation_terms, use that exact English target — do not paraphrase glossary items (e.g. બ્રહ્મ યજ્ઞ → Brahma yagna, આશીર્વાદ → ashirwad, જીવનપ્રાણ → Jeevanpran, સ્વામીબાપા → Swamibapa); prefer glossary mappings over generic English. The speaker often addresses the congregation directly and asks rhetorical questions — keep the direct second-person address and render rhetorical questions as natural English questions, not flattened statements.",
  },
  {
    key: "incomplete_sentences",
    value:
      "Speaker often trails off or uses elliptical Gujarati; prior sentences in this session supply the missing subjects and referents. Translate into natural complete English using that discourse context — live captions should read as continuous speech, not isolated fragments.",
  },
  {
    key: "historical_narration",
    value:
      "In historical recounts and devotional stories, the speaker may enact a character and speak in that character's first-person voice. At each viewpoint shift, identify the active character once before the first-person quotation or thought (for example, 'Arjuna thought...' or 'Vyasa replied...'); then keep that character's viewpoint and pronouns consistent until the story shifts again. Prefer an explicit character name when an English pronoun would be ambiguous. Use concise, idiomatic English with clear subject-verb-object structure instead of word-for-word Gujarati structure: condense only repetition and discourse filler, never material facts, relationships, actions, or devotional meaning. Do not pad the translation or make it sound rambling.",
  },
  {
    key: "number_accuracy",
    value:
      "Spoken quantities are material facts. Carefully distinguish Gujarati બે (2), વીસ (20), and બસો / બસ્સો (200); never drop a zero or reduce the magnitude. In historical phrases, બસો / બસ્સો વરસ પહેલાં or વર્ષ પહેલાં means 'two hundred years ago', વીસ means 'twenty years ago', and બે means 'two years ago'. Preserve the exact spoken quantity in English, including scripture reference numbers and dates.",
  },
  {
    key: "sanskrit_shloks",
    value:
      "The speaker may recite Sanskrit shloks, mantras, or scriptural verse lines (and Gujarati/Hindi scriptural quotations) and then explain them, often repeating the shlok or one phrase of it several times part by part. Render each recitation as a quotation transliterated in Roman script, identical on every repetition; translate only the surrounding Gujarati/Hindi explanation into normal English prose — never force word-for-word English onto the verse itself, and never let verse recitation derail the captions into garbled or invented English. When the speaker cites a scripture by name and reference (e.g. Vachanamrut Gadhada Pratham 21, Shikshapatri shlok 116), keep the transliterated scripture name and the exact spoken reference number.",
  },
];
